#pragma once
#include "HWNDHandler.h"
#include "MyPaint.h"

/*
	Wrapper for HWND Toolbar panel
*/

class ToolbarPanel :
	public HWNDHandler
{
private:

	HIMAGELIST g_hImageList;
	TBBUTTON  buttons[BUTTONS] =
	{
		{I_IMAGECALLBACK, TOOL_LINE,  TBSTATE_ENABLED | TBSTATE_WRAP, BTNS_BUTTON, {0}, 0L, 0},
		{I_IMAGECALLBACK, TOOL_RECT, TBSTATE_ENABLED | TBSTATE_WRAP, BTNS_BUTTON, {0}, 0L, 0},
		{I_IMAGECALLBACK, TOOL_ELLIPSE, TBSTATE_ENABLED | TBSTATE_WRAP, BTNS_BUTTON, {0}, 0L, 0},
		{0, 0, TBSTATE_ENABLED | TBSTATE_WRAP, BTNS_SEP, {0}, 0L, 0},
		{I_IMAGECALLBACK, TOOL_COLORPICKER, TBSTATE_ENABLED | TBSTATE_WRAP, BTNS_BUTTON, {0}, 0L,0},
		{0, 0, TBSTATE_ENABLED | TBSTATE_WRAP, BTNS_SEP, {0}, 0L, 0},
		{I_IMAGECALLBACK, TOOL_PLUS, TBSTATE_ENABLED | TBSTATE_WRAP, BTNS_BUTTON, {0}, 0L,  0},
		{I_IMAGECALLBACK, TOOL_MINUS, TBSTATE_ENABLED | TBSTATE_WRAP, BTNS_BUTTON, {0}, 0L, 0},
		{0, 0, TBSTATE_ENABLED | TBSTATE_WRAP, BTNS_SEP, {0}, 0L, 0},
		{I_IMAGECALLBACK, TOOL_REDO, TBSTATE_ENABLED | TBSTATE_WRAP, BTNS_BUTTON, {0}, 0L, 0},
		{I_IMAGECALLBACK, TOOL_UNDO, TBSTATE_ENABLED | TBSTATE_WRAP, BTNS_BUTTON, {0}, 0L, 0},
	};

public:
	ToolbarPanel(HINSTANCE hInst, HWND parent, const int nCmdShow = SW_SHOW);
	~ToolbarPanel();

	// Inherited via IHandleDialog
	virtual BOOL init() override;
	virtual BOOL show() override;
};

